# In-App schedule posting processor
name = "fbuploadpro-fb-inapp-schedule-processor"
main = "src/index.js"
compatibility_date = "2024-02-05"

[triggers]
crons = ["* * * * *"]

[observability]
enabled = true

[[services]]
binding = "PUBLISHER_WORKER"
service = "fbuploadpro-fb-inapp-schedule-publisher"

[[r2_buckets]]
binding = "USER_MEDIA"
bucket_name = "fbuploadpro-user-media"

