import type { RssTemplateDefinition } from '@/contracts/rss-autoposter'

export const RSS_TEMPLATE_PRESETS: Record<string, { label: string; definition: RssTemplateDefinition }> = {
  'breaking-banner': {
    label: 'Breaking Banner',
    definition: {
      version: 1,
      canvas: { aspectRatio: '4:5', backgroundColor: '#000000' },
      layers: [
        {
          id: 'hero',
          type: 'image',
          binding: 'rss.imageUrl',
          x: 0,
          y: 0,
          width: 1080,
          height: 810,
          fit: 'cover',
        },
        {
          id: 'fade',
          type: 'gradient',
          x: 0,
          y: 520,
          width: 1080,
          height: 830,
          from: 'rgba(0,0,0,0)',
          to: 'rgba(0,0,0,0.95)',
          direction: 'vertical',
        },
        {
          id: 'badge',
          type: 'badge',
          preset: 'breaking_news',
          x: 340,
          y: 720,
        },
        {
          id: 'headline',
          type: 'text',
          binding: 'rss.title',
          x: 60,
          y: 820,
          width: 960,
          height: 400,
          transform: ['uppercase', { maxLines: 6 }],
          baseStyle: {
            fontSize: 48,
            fontWeight: 800,
            fill: '#FFFFFF',
            align: 'center',
            lineHeight: 1.15,
          },
          segments: [
            { match: 'regex', pattern: '\\b(BREAKING|NEWS|ALERT)\\b', fill: '#FFE600' },
          ],
          fallbackSegment: { fill: '#FFFFFF' },
        },
      ],
    },
  },
  'highlight-headline': {
    label: 'Highlight Headline',
    definition: {
      version: 1,
      canvas: { aspectRatio: '4:5', backgroundColor: '#000000' },
      layers: [
        {
          id: 'hero',
          type: 'image',
          binding: 'rss.imageUrl',
          x: 0,
          y: 0,
          width: 1080,
          height: 900,
          fit: 'cover',
        },
        {
          id: 'bar',
          type: 'shape',
          x: 0,
          y: 900,
          width: 1080,
          height: 450,
          fill: '#000000',
        },
        {
          id: 'headline',
          type: 'text',
          binding: 'rss.title',
          x: 80,
          y: 960,
          width: 920,
          height: 320,
          transform: ['uppercase', { maxLines: 5 }],
          baseStyle: {
            fontSize: 44,
            fontWeight: 800,
            fill: '#FFFFFF',
            align: 'left',
            lineHeight: 1.2,
          },
          segments: [
            { match: 'regex', pattern: '\\b(\\$[0-9]+[A-Z]*)\\b', fill: '#FFE600' },
            { match: 'regex', pattern: '\\b(BILLION|MILLION|THOUSAND)\\b', fill: '#00D4FF' },
          ],
          fallbackSegment: { fill: '#FFFFFF' },
        },
      ],
    },
  },
  'quote-card': {
    label: 'Quote Card',
    definition: {
      version: 1,
      canvas: { aspectRatio: '4:5', backgroundColor: '#000000' },
      layers: [
        {
          id: 'hero',
          type: 'image',
          binding: 'rss.imageUrl',
          x: 0,
          y: 0,
          width: 1080,
          height: 700,
          fit: 'cover',
        },
        {
          id: 'fade',
          type: 'gradient',
          x: 0,
          y: 400,
          width: 1080,
          height: 950,
          from: 'rgba(0,0,0,0)',
          to: '#000000',
          direction: 'vertical',
        },
        {
          id: 'headline',
          type: 'text',
          binding: 'rss.title',
          x: 60,
          y: 780,
          width: 960,
          height: 420,
          transform: ['uppercase', { maxLines: 8 }],
          baseStyle: {
            fontSize: 40,
            fontWeight: 800,
            fill: '#FFFFFF',
            align: 'center',
            lineHeight: 1.2,
          },
          segments: [
            { match: 'regex', pattern: '\\b(TRUMP|PRESIDENT|DELIVERED)\\b', fill: '#FFE600' },
          ],
          fallbackSegment: { fill: '#FFFFFF' },
        },
      ],
    },
  },
  'sidebar-news': {
    label: 'Sidebar News',
    definition: {
      version: 1,
      canvas: { aspectRatio: '4:5', backgroundColor: '#000000' },
      layers: [
        {
          id: 'hero',
          type: 'image',
          binding: 'rss.imageUrl',
          x: 0,
          y: 0,
          width: 1080,
          height: 720,
          fit: 'cover',
        },
        {
          id: 'sidebar',
          type: 'shape',
          x: 0,
          y: 720,
          width: 24,
          height: 630,
          fill: '#00D4FF',
        },
        {
          id: 'panel',
          type: 'shape',
          x: 0,
          y: 720,
          width: 1080,
          height: 630,
          fill: '#000000',
        },
        {
          id: 'headline',
          type: 'text',
          binding: 'rss.title',
          x: 48,
          y: 780,
          width: 984,
          height: 480,
          transform: ['uppercase', { maxLines: 7 }],
          baseStyle: {
            fontSize: 42,
            fontWeight: 800,
            fill: '#FFFFFF',
            align: 'left',
            lineHeight: 1.15,
          },
          segments: [
            { match: 'regex', pattern: "'[^']+'", fill: '#00D4FF' },
          ],
          fallbackSegment: { fill: '#FFFFFF' },
        },
      ],
    },
  },
  'brand-overlay': {
    label: 'Brand Overlay',
    definition: {
      version: 1,
      canvas: { aspectRatio: '4:5', backgroundColor: '#111111' },
      layers: [
        {
          id: 'hero',
          type: 'image',
          binding: 'rss.imageUrl',
          x: 0,
          y: 0,
          width: 1080,
          height: 1350,
          fit: 'cover',
        },
        {
          id: 'fade',
          type: 'gradient',
          x: 0,
          y: 800,
          width: 1080,
          height: 550,
          from: 'rgba(0,0,0,0)',
          to: 'rgba(0,0,0,0.85)',
          direction: 'vertical',
        },
        {
          id: 'logo',
          type: 'logo',
          binding: 'brand.logo',
          x: 48,
          y: 48,
          width: 120,
          height: 120,
        },
        {
          id: 'headline',
          type: 'text',
          binding: 'rss.title',
          x: 80,
          y: 1050,
          width: 920,
          height: 240,
          transform: ['uppercase', { maxLines: 4 }],
          baseStyle: {
            fontSize: 46,
            fontWeight: 800,
            fill: '#FFFFFF',
            align: 'center',
            lineHeight: 1.2,
          },
          fallbackSegment: { fill: '#FFFFFF' },
        },
      ],
    },
  },
  'inset-badge': {
    label: 'Inset Badge',
    definition: {
      version: 1,
      canvas: { aspectRatio: '4:5', backgroundColor: '#000000' },
      layers: [
        {
          id: 'hero',
          type: 'image',
          binding: 'rss.imageUrl',
          x: 0,
          y: 0,
          width: 1080,
          height: 820,
          fit: 'cover',
        },
        {
          id: 'inset',
          type: 'image',
          binding: 'rss.imageUrl',
          x: 48,
          y: 620,
          width: 200,
          height: 200,
          fit: 'cover',
          mask: 'circle',
          borderRadius: 100,
        },
        {
          id: 'badge',
          type: 'badge',
          preset: 'breaking_news',
          x: 280,
          y: 700,
        },
        {
          id: 'panel',
          type: 'shape',
          x: 0,
          y: 820,
          width: 1080,
          height: 530,
          fill: '#000000',
        },
        {
          id: 'headline',
          type: 'text',
          binding: 'rss.title',
          x: 60,
          y: 900,
          width: 960,
          height: 380,
          transform: ['uppercase', { maxLines: 6 }],
          baseStyle: {
            fontSize: 44,
            fontWeight: 800,
            fill: '#FFFFFF',
            align: 'center',
            lineHeight: 1.15,
          },
          fallbackSegment: { fill: '#FFFFFF' },
        },
      ],
    },
  },
}

export function getCanvasDimensions(aspect: '4:5' | '1:1' | '16:9') {
  if (aspect === '1:1') return { width: 1080, height: 1080 }
  if (aspect === '16:9') return { width: 1200, height: 675 }
  return { width: 1080, height: 1350 }
}
