# ADU posting deploy step 2
name = "fbuploadpro-adu-2-publish-processor"
main = "src/index.js"
compatibility_date = "2024-02-05"

[triggers]
crons = ["* * * * *"]

[observability]
enabled = true

[[services]]
binding = "PUBLISHER_WORKER"
service = "fbuploadpro-adu-1-publisher"
