name = "fbuploadprov2-prod-posting-03-publisher"
main = "src/index.js"
compatibility_date = "2024-02-05"

[[durable_objects.bindings]]
name = "POSTING_PUBLISH_STATE_DO"
class_name = "PostingPublishStateDO"

[[r2_buckets]]
binding = "POSTING_MEDIA_BUCKET"
bucket_name = "fbuploadprov2-prod-posting-media"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["PostingPublishStateDO"]

