-- Posting pipeline: durable job row + append-only events for observability
-- Date: 2026-04-21

create table if not exists public.posting_jobs (
  job_id uuid primary key,
  trace_id uuid,
  mode text not null check (mode in ('prod', 'test')),
  agency_id uuid references public.users(id) on delete set null,
  page_id uuid not null references public.pages(id) on delete cascade,
  reel_internal_id bigint not null references public.reels(id) on delete cascade,
  status text not null default 'queued_for_download'
    check (status in (
      'queued_for_download',
      'downloading',
      'download_ready',
      'publishing',
      'posted',
      'failed_terminal',
      'retry_scheduled'
    )),
  payload jsonb not null default '{}'::jsonb,
  error_code text,
  error_message text,
  attempt_download int not null default 0,
  attempt_publish int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_posting_jobs_active_page_reel
  on public.posting_jobs (page_id, reel_internal_id)
  where status not in ('posted', 'failed_terminal');

create index if not exists idx_posting_jobs_status_created
  on public.posting_jobs (status, created_at desc);

create index if not exists idx_posting_jobs_page_id
  on public.posting_jobs (page_id);

create table if not exists public.pipeline_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  job_id uuid,
  trace_id uuid,
  service text not null,
  event_type text not null,
  status text,
  error_code text,
  error_message text,
  duration_ms int,
  node_id text,
  env_name text,
  mode text,
  page_id uuid,
  reel_internal_id bigint,
  payload jsonb not null default '{}'::jsonb
);

create index if not exists idx_pipeline_events_created_at
  on public.pipeline_events (created_at desc);

create index if not exists idx_pipeline_events_job_id
  on public.pipeline_events (job_id);

create index if not exists idx_pipeline_events_service_event
  on public.pipeline_events (service, event_type, created_at desc);

create index if not exists idx_pipeline_events_error_code
  on public.pipeline_events (error_code)
  where error_code is not null;

create trigger tr_posting_jobs_updated_at
  before update on public.posting_jobs
  for each row execute procedure public.update_updated_at_column();

alter table public.posting_jobs enable row level security;
alter table public.pipeline_events enable row level security;

create policy "Service role full access posting_jobs"
  on public.posting_jobs
  for all
  to service_role
  using (true)
  with check (true);

create policy "Super Admin read posting_jobs"
  on public.posting_jobs
  for select
  using (public.get_my_role() = 'super_admin');

create policy "Service role full access pipeline_events"
  on public.pipeline_events
  for all
  to service_role
  using (true)
  with check (true);

create policy "Super Admin read pipeline_events"
  on public.pipeline_events
  for select
  using (public.get_my_role() = 'super_admin');
