name = "fbuploadprov2-v2-downloader-service"
main = "src/index.js"
compatibility_date = "2024-02-05"

[observability]
enabled = true

[[r2_buckets]]
binding = "POSTING_MEDIA_BUCKET"
bucket_name = "fbuploadprov2-v2-posting-media"

[[containers]]
class_name = "DownloaderContainer"
image = "./container-api/Dockerfile"
max_instances = 350

[[durable_objects.bindings]]
name = "DOWNLOADER_CONTAINER"
class_name = "DownloaderContainer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DownloaderContainer"]
