name = "fbuploadprov2-v2-publish-processor"
main = "src/index.js"
compatibility_date = "2024-02-05"

[triggers]
crons = ["* * * * *"]

[observability]
enabled = true

[[services]]
binding = "PUBLISHER_WORKER"
service = "fbuploadprov2-v2-publisher"
