name = "fbuploadprov2-v2-reel-geter"
main = "src/index.js"
compatibility_date = "2024-02-05"

[observability]
enabled = true

[[services]]
binding = "DOWNLOADER_SERVICE"
service = "fbuploadprov2-v2-downloader-service"

[[r2_buckets]]
binding = "POSTING_MEDIA_BUCKET"
bucket_name = "fbuploadprov2-v2-posting-media"
