name: SonarQube Cloud Analysis

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - integrate_sonarqube_scanner
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  sonar:
    name: Official SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Disabling shallow clone is required for SonarQube to analyze PR changes and blame
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@7088e561eb65bb68695d245aa206f005ef30921d # v4.1.0
        with:
          version: 9.15.9

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Run Tests
        run: pnpm turbo run test

      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@d209202bc7d53ff1cc128f7f907dac145c9d6ae9 # v8.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
